-- CUP-FICCT - Schema final de produccion desde cero
-- PostgreSQL
-- Este script crea la estructura actual del sistema desde cero.
-- No incluye disparadores, procedimientos almacenados, datos de ejemplo
-- ni consultas de documentacion.
--
-- Incluye:
-- - Tablas actuales usadas por Laravel/Inertia.
-- - PK, FK, UNIQUE, CHECK e indices.
-- - Funcion calcular_grupos.
-- - Vistas promedio_por_materia y resultado_final_postulante.

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    correo VARCHAR(150) NOT NULL UNIQUE,
    email_verified_at TIMESTAMP(0),
    password_hash VARCHAR(255) NOT NULL,
    telefono VARCHAR(20),
    sexo CHAR(1),
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    estado_acceso VARCHAR(20) NOT NULL DEFAULT 'HABILITADO',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remember_token VARCHAR(100),
    CONSTRAINT usuario_sexo_check CHECK (sexo IN ('M', 'F', 'O')),
    CONSTRAINT usuario_intentos_fallidos_check CHECK (intentos_fallidos >= 0),
    CONSTRAINT usuario_estado_acceso_check CHECK (estado_acceso IN ('HABILITADO', 'SUSPENDIDO', 'BLOQUEADO')),
    CONSTRAINT usuario_correo_check CHECK (correo ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE password_reset_tokens (
    email VARCHAR(150) PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0),
    CONSTRAINT password_reset_tokens_email_check CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE sessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

CREATE INDEX sessions_user_id_index ON sessions (user_id);
CREATE INDEX sessions_last_activity_index ON sessions (last_activity);

CREATE TABLE cache (
    key VARCHAR(255) PRIMARY KEY,
    value TEXT NOT NULL,
    expiration BIGINT NOT NULL
);

CREATE INDEX cache_expiration_index ON cache (expiration);

CREATE TABLE cache_locks (
    key VARCHAR(255) PRIMARY KEY,
    owner VARCHAR(255) NOT NULL,
    expiration BIGINT NOT NULL
);

CREATE INDEX cache_locks_expiration_index ON cache_locks (expiration);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    attempts SMALLINT NOT NULL,
    reserved_at INTEGER,
    available_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
);

CREATE INDEX jobs_queue_index ON jobs (queue);

CREATE TABLE job_batches (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    total_jobs INTEGER NOT NULL,
    pending_jobs INTEGER NOT NULL,
    failed_jobs INTEGER NOT NULL,
    failed_job_ids TEXT NOT NULL,
    options TEXT,
    cancelled_at INTEGER,
    created_at INTEGER NOT NULL,
    finished_at INTEGER
);

CREATE TABLE failed_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL UNIQUE,
    connection VARCHAR(255) NOT NULL,
    queue VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    exception TEXT NOT NULL,
    failed_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX failed_jobs_connection_queue_failed_at_index ON failed_jobs (connection, queue, failed_at);

CREATE TABLE migrations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration VARCHAR(255) NOT NULL,
    batch INTEGER NOT NULL
);

CREATE TABLE rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permiso (
    id_permiso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    modulo VARCHAR(50) NOT NULL,
    accion VARCHAR(50) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT permiso_accion_check CHECK (accion IN ('CREAR', 'LEER', 'ACTUALIZAR', 'ELIMINAR', 'EJECUTAR'))
);

CREATE TABLE rol_usuario (
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_rol BIGINT NOT NULL REFERENCES rol(id_rol) ON DELETE CASCADE,
    fecha_asignacion TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP(0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id_usuario, id_rol),
    CONSTRAINT rol_usuario_fecha_expiracion_check CHECK (fecha_expiracion IS NULL OR fecha_expiracion >= fecha_asignacion)
);

CREATE TABLE rol_permiso (
    id_rol BIGINT NOT NULL REFERENCES rol(id_rol) ON DELETE CASCADE,
    id_permiso BIGINT NOT NULL REFERENCES permiso(id_permiso) ON DELETE CASCADE,
    fecha_asignacion TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE sesion (
    id_sesion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    token_sesion VARCHAR(255) NOT NULL UNIQUE,
    refresh_token VARCHAR(255) UNIQUE,
    fecha_inicio TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP(0),
    fecha_cierre TIMESTAMP(0),
    user_agent TEXT,
    ip_origen INET,
    CONSTRAINT sesion_fecha_expiracion_check CHECK (fecha_expiracion IS NULL OR fecha_expiracion > fecha_inicio),
    CONSTRAINT sesion_fecha_cierre_check CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_inicio)
);

CREATE TABLE gestion_academica (
    id_gestion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT gestion_academica_fechas_check CHECK (fecha_fin > fecha_inicio)
);

CREATE TABLE carrera (
    id_carrera BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE cupo_carrera (
    id_cupo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrera BIGINT NOT NULL REFERENCES carrera(id_carrera),
    id_gestion BIGINT NOT NULL REFERENCES gestion_academica(id_gestion),
    cupo_maximo INTEGER NOT NULL,
    UNIQUE (id_carrera, id_gestion),
    CONSTRAINT cupo_carrera_cupo_maximo_check CHECK (cupo_maximo > 0)
);

CREATE TABLE postulante (
    id_postulante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    fecha_nacimiento DATE NOT NULL,
    direccion TEXT,
    colegio_procedencia VARCHAR(150),
    ciudad VARCHAR(80),
    documentacion_completa BOOLEAN NOT NULL DEFAULT FALSE,
    presento_titulo_bachiller BOOLEAN NOT NULL DEFAULT FALSE,
    presento_fotocopia_carnet BOOLEAN NOT NULL DEFAULT FALSE,
    documentacion_validada BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_validacion_documentos TIMESTAMP(0),
    validado_por BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    creado_por_admin BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_pago BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE docente (
    id_docente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    profesional_area BOOLEAN NOT NULL DEFAULT FALSE,
    maestria BOOLEAN NOT NULL DEFAULT FALSE,
    diplomado_educacion_superior BOOLEAN NOT NULL DEFAULT FALSE,
    maestria_educacion_superior BOOLEAN NOT NULL DEFAULT FALSE,
    contratado BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT docente_contratado_check CHECK (contratado = FALSE OR maestria_educacion_superior = TRUE)
);

CREATE TABLE materia_cup (
    id_materia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE docente_habilitacion_materia (
    id_habilitacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_docente BIGINT NOT NULL REFERENCES docente(id_docente) ON DELETE CASCADE,
    id_materia BIGINT NOT NULL REFERENCES materia_cup(id_materia) ON DELETE CASCADE,
    tipo_habilitacion VARCHAR(30) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT docente_habilitacion_tipo_check CHECK (tipo_habilitacion IN ('PROFESIONAL_AREA', 'DIPLOMADO', 'MAESTRIA')),
    CONSTRAINT docente_habilitacion_unique UNIQUE (id_docente, id_materia, tipo_habilitacion)
);

CREATE INDEX docente_habilitacion_materia_id_docente_index ON docente_habilitacion_materia (id_docente);
CREATE INDEX docente_habilitacion_materia_id_materia_index ON docente_habilitacion_materia (id_materia);
CREATE INDEX docente_habilitacion_materia_activo_index ON docente_habilitacion_materia (activo);

CREATE TABLE aula (
    id_aula BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    capacidad INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT aula_capacidad_check CHECK (capacidad > 0)
);

CREATE TABLE horario (
    id_horario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turno VARCHAR(20) NOT NULL,
    hora_inicio TIME(0) NOT NULL,
    hora_fin TIME(0) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT horario_horas_check CHECK (hora_fin > hora_inicio),
    CONSTRAINT horario_turno_check CHECK (turno IN ('MANANA', 'TARDE', 'NOCHE')),
    CONSTRAINT horario_turno_horas_unique UNIQUE (turno, hora_inicio, hora_fin)
);

CREATE TABLE grupo_academico (
    id_grupo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_gestion BIGINT NOT NULL REFERENCES gestion_academica(id_gestion),
    nombre VARCHAR(50) NOT NULL,
    turno VARCHAR(20),
    capacidad_maxima INTEGER NOT NULL DEFAULT 70,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (id_gestion, nombre),
    CONSTRAINT grupo_academico_capacidad_maxima_check CHECK (capacidad_maxima > 0 AND capacidad_maxima <= 70),
    CONSTRAINT grupo_academico_turno_check CHECK (turno IN ('MANANA', 'TARDE', 'NOCHE'))
);

CREATE TABLE asignacion_academica (
    id_asignacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupo BIGINT NOT NULL REFERENCES grupo_academico(id_grupo),
    id_materia BIGINT NOT NULL REFERENCES materia_cup(id_materia),
    id_docente BIGINT NOT NULL REFERENCES docente(id_docente),
    id_aula BIGINT NOT NULL REFERENCES aula(id_aula),
    id_horario BIGINT NOT NULL REFERENCES horario(id_horario),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (id_grupo, id_materia),
    UNIQUE (id_docente, id_horario),
    UNIQUE (id_aula, id_horario)
);

CREATE TABLE postulacion (
    id_postulacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulante BIGINT NOT NULL REFERENCES postulante(id_postulante),
    id_gestion BIGINT NOT NULL REFERENCES gestion_academica(id_gestion),
    id_carrera_opcion1 BIGINT NOT NULL REFERENCES carrera(id_carrera),
    id_carrera_opcion2 BIGINT REFERENCES carrera(id_carrera),
    id_carrera_admitida BIGINT REFERENCES carrera(id_carrera),
    id_grupo BIGINT REFERENCES grupo_academico(id_grupo),
    estado_admision VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_postulacion TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado_proceso VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE_VALIDACION',
    turno_preferido VARCHAR(20),
    UNIQUE (id_postulante, id_gestion),
    CONSTRAINT postulacion_carreras_distintas_check CHECK (id_carrera_opcion2 IS NULL OR id_carrera_opcion1 <> id_carrera_opcion2),
    CONSTRAINT postulacion_estado_admision_check CHECK (estado_admision IN ('PENDIENTE', 'ADMITIDO', 'NO_ADMITIDO')),
    CONSTRAINT postulacion_turno_preferido_check CHECK (turno_preferido IN ('MANANA', 'TARDE', 'NOCHE'))
);

CREATE TABLE pago_inscripcion (
    id_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulacion BIGINT NOT NULL REFERENCES postulacion(id_postulacion),
    monto NUMERIC(10, 2) NOT NULL,
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    pasarela VARCHAR(50) NOT NULL,
    numero_transaccion VARCHAR(150) NOT NULL UNIQUE,
    codigo_autorizacion VARCHAR(100),
    codigo_error VARCHAR(100),
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_inicio TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_confirmacion TIMESTAMP(0),
    CONSTRAINT pago_inscripcion_monto_check CHECK (monto > 0),
    CONSTRAINT pago_inscripcion_pasarela_check CHECK (pasarela IN ('PAYPAL', 'STRIPE')),
    CONSTRAINT pago_inscripcion_estado_pago_check CHECK (estado_pago IN ('PENDIENTE', 'PROCESANDO', 'APROBADO', 'RECHAZADO', 'CANCELADO')),
    CONSTRAINT pago_inscripcion_fecha_confirmacion_check CHECK (fecha_confirmacion IS NULL OR fecha_confirmacion >= fecha_inicio)
);

CREATE TABLE nota (
    id_nota BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_postulacion BIGINT NOT NULL REFERENCES postulacion(id_postulacion),
    id_materia BIGINT NOT NULL REFERENCES materia_cup(id_materia),
    nro_examen INTEGER NOT NULL,
    nota NUMERIC(5, 2) NOT NULL,
    fecha_registro TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registrado_por BIGINT REFERENCES usuario(id_usuario),
    UNIQUE (id_postulacion, id_materia, nro_examen),
    CONSTRAINT nota_nro_examen_check CHECK (nro_examen BETWEEN 1 AND 3),
    CONSTRAINT nota_nota_check CHECK (nota BETWEEN 0 AND 100)
);

CREATE TABLE log_auditoria (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(100) NOT NULL,
    operacion VARCHAR(20) NOT NULL,
    id_registro VARCHAR(50),
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    id_usuario BIGINT REFERENCES usuario(id_usuario),
    user_agent TEXT,
    fecha_operacion TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_origen INET,
    CONSTRAINT log_auditoria_operacion_check CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT'))
);

CREATE FUNCTION calcular_grupos(total_inscritos INTEGER)
RETURNS INTEGER AS
$$
BEGIN
    RETURN CEIL(total_inscritos / 70.0);
END;
$$ LANGUAGE plpgsql;

CREATE VIEW promedio_por_materia AS
SELECT
    po.id_postulacion,
    u.ci,
    u.nombre,
    u.apellido,
    m.nombre AS materia,
    ROUND(AVG(n.nota), 2) AS promedio_materia
FROM nota n
JOIN postulacion po ON n.id_postulacion = po.id_postulacion
JOIN postulante p ON po.id_postulante = p.id_postulante
JOIN usuario u ON p.id_usuario = u.id_usuario
JOIN materia_cup m ON n.id_materia = m.id_materia
GROUP BY
    po.id_postulacion,
    u.ci,
    u.nombre,
    u.apellido,
    m.nombre;

CREATE VIEW resultado_final_postulante AS
SELECT
    po.id_postulacion,
    u.ci,
    u.nombre,
    u.apellido,
    ROUND(AVG(n.nota), 2) AS promedio_final,
    CASE
        WHEN AVG(n.nota) >= 60 THEN 'APROBADO'
        ELSE 'REPROBADO'
    END AS estado_final
FROM postulacion po
JOIN postulante p ON po.id_postulante = p.id_postulante
JOIN usuario u ON p.id_usuario = u.id_usuario
JOIN nota n ON po.id_postulacion = n.id_postulacion
GROUP BY
    po.id_postulacion,
    u.ci,
    u.nombre,
    u.apellido;
